### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by gugek** [rd-alliance/metadata-directory#31]
Would there be an tracker that would work for the directory? snippet would then need to be added to appropriate templates.

**Comment by rkoskela** [comment]
Interesting idea - the templates are being updated this week for better usability and eye appeal - I'll
check to see if analytics could also be added.  Thanks!

**Comment by gugek** [comment]
@triniq added the tracking code...is it collecting? If so we can close this.

**Comment by rkoskela** [comment]
Yes, it is collecting - ok to close.

Rebecca

**Comment by gugek** [comment]
Added in: https://github.com/rd-alliance/metadata-directory/commit/3161f12c5cbc5b35defa1c75603adc00c6c4e205
