### ISSUE TITLE
Add CERIF standard

### ISSUE THREAD

**Issue by alex-ball** [rd-alliance/metadata-directory#35]
Category: General Research

Links:

  * [Home page](http://eurocris.org/Index.php?page=CERIFreleases&t=1)

Description: The Common European Research Information Format is the standard that the EU recommends to its member states for recording information about research activity. Since version 1.6 it has included specific support for recording metadata for datasets.

Sponsor: EuroCRIS

Tools: Current Research Information System software that uses CERIF includes

* Elsevier PURE
* Avedas CONVERIS
* Symplectic ELEMENTS

Use cases:

* OpenAIRE

**Comment by gugek** [comment]
Implemented in #47 .
